version: "3.8"

services:
  mongo:
    image: mongo:6
    container_name: mongo
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db
    networks:
      - automation-network

  redis:
    image: redis:7-alpine
    container_name: redis
    ports:
      - "6379:6379"
    networks:
      - automation-network

  jaeger:
    image: jaegertracing/all-in-one:1.57.0
    container_name: jaeger
    ports:
      - "16686:16686"
      - "4317:4317"
      - "4318:4318"
    environment:
      COLLECTOR_OTLP_ENABLED: "true"
    networks:
      - automation-network

  registry-service:
    image: ghcr.io/ondc-official/automation-registry:dev-1.0.2
    platform: linux/amd64
    container_name: registry-service
    ports:
      - "8080:8080"
    env_file:
      - ./docker-env/registry-service.env
    networks:
      - automation-network
    depends_on:
      - mongo

  db-service:
    image: ghcr.io/ondc-official/automation-db:dev-1.0.0-9ce8c80
    platform: linux/amd64
    container_name: db-service
    ports:
      - "5001:5001"
    env_file:
      - ./docker-env/db-service.env
    networks:
      - automation-network
    depends_on:
      - mongo
      - jaeger

  config-service:
    image: ghcr.io/ondc-official/automation-config-service:prod-1.0.0-0d20f10
    platform: linux/amd64
    container_name: config-service
    ports:
      - "5556:5556"
    env_file:
      - ./docker-env/config-service.env
    networks:
      - automation-network
    depends_on:
      - redis
      - db-service
      - jaeger

  playground-mock-service:
    image: ghcr.io/ondc-official/automation-mock-playground-service:dev-1.0.0-250ff4e
    platform: linux/amd64
    container_name: playground-mock-service
    ports:
      - "3031:3000"
    env_file:
      - ./docker-env/playground-mock-service.env
    networks:
      - automation-network
    depends_on:
      - redis
      - config-service

  recorder-service:
    image: ghcr.io/ondc-official/automation-recorder-service:dev-0.0.3
    platform: linux/amd64
    container_name: recorder-service
    ports:
      - "8090:8090"
      - "8089:8089"
    env_file:
      - ./docker-env/recorder-service.env
    networks:
      - automation-network
    depends_on:
      - redis
      - db-service

  report-pramaan-buyer:
    image: ghcr.io/ondc-official/automation-report-pramaan-buyer:dev-0.0.7
    platform: linux/amd64
    container_name: report-pramaan-buyer
    ports:
      - "3005:3005"
    env_file:
      - ./docker-env/report-pramaan-buyer.env
    networks:
      - automation-network
    depends_on:
      - mongo

  report-pramaan-seller:
    image: ghcr.io/ondc-official/automation-report-pramaan-seller:dev-0.0.7
    platform: linux/amd64
    container_name: report-pramaan-seller
    ports:
      - "3006:3005"
    env_file:
      - ./docker-env/report-pramaan-seller.env
    networks:
      - automation-network
    depends_on:
      - mongo

  report-service:
    image: ghcr.io/ondc-official/automation-report-service:dev-1.0.0-398efa2
    platform: linux/amd64
    container_name: report-service
    ports:
      - "3000:3000"
    env_file:
      - ./docker-env/report-service.env
    networks:
      - automation-network
    depends_on:
      - redis
      - db-service
      - report-pramaan-buyer
      - report-pramaan-seller
      - jaeger

  automation-user-management:
    image: ghcr.io/ondc-official/automation-user-management:dev-0.0.0-3567db7
    platform: linux/amd64
    container_name: automation-user-management
    ports:
      - "8082:8082"
    env_file:
      - ./docker-env/automation-user-management.env
    networks:
      - automation-network
    depends_on:
      - mongo

  form-service:
    image: ghcr.io/ondc-official/automation-form-service:dev-1.0.0-7792084
    platform: linux/amd64
    container_name: form-service
    ports:
      - "3300:3300"
    env_file:
      - ./docker-env/form-service.env
    networks:
      - automation-network
    depends_on:
      - redis

  backoffice-backend:
    image: ghcr.io/ondc-official/automation-backoffice-backend:dev-1.0.0-2439274
    platform: linux/amd64
    container_name: backoffice-backend
    ports:
      - "5200:5000"
    env_file:
      - ./docker-env/backoffice-backend.env
    networks:
      - automation-network
    depends_on:
      - redis
      - db-service
      - jaeger

  backoffice-frontend:
    build:
      context: .
      dockerfile: ./dockerfiles/backoffice-frontend.Dockerfile
      args:
        VITE_BACKEND_URL: http://localhost:5200
        VITE_BASE_URL: /backoffice
    container_name: backoffice-frontend
    ports:
      - "5100:5001"
    networks:
      - automation-network

  ui-backend:
    image: ghcr.io/ondc-official/automation-frontend/backend:dev-0.0.0-a5c34b3
    platform: linux/amd64
    container_name: ui-backend
    ports:
      - "3034:5000"
    env_file:
      - ./docker-env/ui-backend.env
    networks:
      - automation-network
    depends_on:
      - redis
      - db-service
      - config-service
      - report-service
      - playground-mock-service
      - automation-user-management
      - jaeger

  ui-frontend:
    build:
      context: .
      dockerfile: ./dockerfiles/ui-frontend.Dockerfile
      args:
        VITE_BAP_URL: http://localhost:3032/buyer
        VITE_BACKEND_URL: http://localhost:3034
        VITE_BASE_URL: http://localhost:3032
        VITE_BPP_URL: http://localhost:3032/seller
        VITE_DB_SERVICE_API_KEY: D33A76D111B4BDFCB96A2AC34B85E
        VITE_DEVELOPER_GUIDE_BACKEND_URL: http://localhost:8082
    container_name: ui-frontend
    ports:
      - "3035:5001"
    networks:
      - automation-network

volumes:
  mongo_data:

networks:
  automation-network:
    driver: bridge
