version: "3.8"


services:
  automation-db:
    # image: mofahsan/automation-db:latest
    build: ./automation-db
    ports:
      - 8080:8080
    networks:
      - automation-network 
    depends_on:
      - yugabyte


  automation-api-service:
    build: ./automation-api-service
    ports:
      - "3032:3000"
    # env_file:
    #   - .env
    restart: always
    networks:
      - automation-network
    depends_on:
      - redis

  automation-mock-service:
    build: ./automation-mock-service
    ports:
      - "3031:8000"
    # env_file:
    #   - .env
    restart: always
    networks:
      - automation-network
    depends_on:
      - redis

  automation-report-service:
    build: ./automation-report-service
    ports:
      - "3000:3000"
    networks:
      - automation-network
    depends_on:
      - redis

  automation-ui-backend:
    build:
      context: ./automation-frontend/backend
      dockerfile: Dockerfile
    container_name: automation-ui-backend
    ports:
      - "3034:5000"
    # env_file:
    #   - backend/.env
    restart: always
    networks:
      - automation-network
    depends_on:
      - redis

  automation-ui-frontend:
    build:
      context: ./automation-frontend/frontend
      dockerfile: Dockerfile
    container_name: automation-ui-frontend
    ports:
      - "3035:5001"
    # env_file:
    #   - frontend/.env
    restart: always
    networks:
      - automation-network

  backoffice-backend:
    restart: always
    build: ./automation-backoffice/backend
    ports:
      - 5200:5000
    # env_file:
    #   - backend/.env
    depends_on:
      - redis

  backoffice-frontend:
    restart: always
    build: ./automation-backoffice/frontend
    ports:
      - 5100:5001
    # env_file:
    #   - frontend/.env

  redis:
    image: redis:6.2
    container_name: redis
    ports:
      - "6379:6379"
    networks:
      - automation-network 

  yugabyte:
    image: yugabytedb/yugabyte:latest
    container_name: yugabyte
    command: [ "/home/yugabyte/bin/yugabyted", "start", "--base_dir=/mnt/data", "--daemon=false" ]
    ports:
      - "7001:7000"  # Master UI
      - "9000:9000"  # TServer UI
      - "5433:5433"  # PostgreSQL API
      - "9042:9042"  # YCQL API
    volumes:
      - yugabyte_data:/mnt/data
    networks:
      - automation-network 


volumes:
  yugabyte_data:

networks:
  automation-network:
    driver: bridge