name: Protocol Workbench Issues
description: Report bugs, suggest improvements, or request new features
title: "[Issue]"
body:
  - type: dropdown
    id: issue_type
    attributes:
      label: Type of Issue
      description: Select the type of issue you're reporting
      options:
        - Question / Clarification
        - Bug Report
        - Feature Request
        - Enhancement Suggestion
        - Proposed Use Case
    validations:
      required: true

  - type: textarea
    id: summary
    attributes:
      label: Summary
      description: A brief summary of the issue or suggestion. Describe what you're seeing or what you're proposing.
      placeholder: "e.g., Flow fails on /select with invalid payment object"
    validations:
      required: true

  - type: textarea
    id: expected_behavior
    attributes:
      label: Expected Behavior
      description: What should happen instead? What’s the ideal outcome?
      placeholder: "e.g., The tool should validate and reject the payload with a clear error"

  - type: textarea
    id: steps_to_reproduce
    attributes:
      label: Steps to Reproduce / Context
      description: List the steps, API calls, or context to help us understand or replicate the issue.
      placeholder: |
        1. Call `POST /search` with X payload  
        2. Receive Y response  
        3. Expected Z behavior

  - type: textarea
    id: attachments
    attributes:
      label: Payloads / Logs / Screenshots (if applicable)
      description: Include relevant API responses, screenshots, or logs to help us debug.

  - type: input
    id: domain
    attributes:
      label: Domain
      description: Mention the domain (e.g., RET10, LOG10, TRV11, etc.)
      placeholder: "e.g., RET10"

  - type: input
    id: version
    attributes:
      label: Version
      placeholder: "e.g., 1.2.5"

  - type: input
    id: test_type
    attributes:
      attributes:
      label: Testing Mode
      placeholder: "e.g., Schema or Flow"

  - type: input
    id: scenario
    attributes:
      label: Scenario Name
      placeholder: "Optional – e.g., Search-Select-Init for Grocery"

  - type: textarea
    id: additional_notes
    attributes:
      label: Additional Notes
      placeholder: "Any other context, links, or suggestions"

  - type: input
    id: reported_by
    attributes:
      label: Reported By (GitHub Handle)
      placeholder: "@your-username"
    validations:
      required: true
